version: "3.8"

services:
  mongo:
    image: mongo
    container_name: library-mongo
    ports:
      - "27017:27017"

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
